# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d24692be04ce7102b4c34761843a9d4c80b31854be5e20ad6851c79fd6028b2abc56b997bf1339b6309ca6d9f7f58257c92a220c2ce028eb9405e34ccb0fceb

test:
  secret_key_base: f6f14f48c9720a632aaf5c9902bca96a638c1e44fcf0dd4f65739526c4e279a9b7f8fcdafbfa48e37a91305b4cd838b8a29b119a43443db1e77a8a2206644eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
